### ISSUE TITLE
MSVC can not recognize the value type when calling add_value

### ISSUE THREAD

**Issue by BriFuture** [simulton/gpds#3]
Hi, I figured out that why MSVC failed to compile when `gpds::container::add_value` is called.

I made a simple test https://gist.github.com/BriFuture/259844ddcbfe6891ab9207a23a0a065f, the code are mostly copied from GPDS. Notice, in the `main` function, first of these sentence could be compiled successfully:

```cpp
    add_value("test", value()); // able to compile
//    add_value("test", 1);     // fail to compile
//    add_value("test", 1.0);   // fail to compile
//    add_value("test", true);  // fail to compile
```

So, I just want to know, is there a mechanisim that gcc could automatically convert the type `int`, type `double`, type `bool` or type `std::string` as type `value` ?

**Comment by Tectu** [comment]
> So, I just want to know, is there a mechanisim that gcc could automatically convert the type int, type double, type bool or type std::string as type value ?

The GPDS library is not relying on any GCC specific behavior or extensions. The library has been written with the goal in mind to only require a bare C++17 compliant compiler.
Internally, the `gpds::value` class uses `std::variant`: https://github.com/simulton/GPDS/blob/33ef72e2babc02d9aa9baec44825556c1d081b3c/lib/include/gpds/value.hpp#L149

According to [cppreference.com](https://en.cppreference.com/w/cpp/compiler_support), MSVC supports this since version 19.10 (VS 2017 15.0)

I currently don't have any MSVC environment ready to run - can you try to compile a simple example program using `std::variant` using your compiler?
Unfortunately I am not very experience with MSVC. Might it be an automatic template type deduction issue? Can you try to explicitly state the template type?
```
add_value<int>("test", 1);
add_value<bool>("test", true);
```
This is pretty much just a wild guess as I want to try to help as best as I can. Maybe somebody with more MSVC experience could step in here?

**Comment by BriFuture** [comment]
1. MSVC 15.9.24, then it supports c++17.
2. fail to compile even though explicitly state the template typ
```
add_value<bool>("test", true);  // fail to compile
add_value<int>("test", 1);     // fail to compile
```
3. following codes are able to compile:
```
int main() {
    auto v = value();
    v.set(1);
    v.set(1.0);
    v.set(true);
    add_value("test", v); // able to compile

    std::variant<
        bool,
        int,
        double,
        std::string,
        container *
    > m_value;
    m_value = 1;
    m_value = "test";
    m_value = true; // able to compile
    return 0;
}
```

**Comment by BriFuture** [comment]
Well, I'm still confused that how compiler know whether to convert types automatically.

the signature of `add_value` is 
```cpp
template<class T>
value& add_value(const std::string& key, T&& value)
```
so this function could accept random type for second parameter as rvalue, is it right?

But the multimap `values` is defined as `std::multimap<gString, value> values;` 
then `gpds::value` not integer or double could be inserted into the multimap. 

Although `gpds::value` internally uses `std::variant`, it doesnt make sense that integer/double/std::string could be converted as `gpds::value`.

**Comment by Tectu** [comment]
The compiler can deduce the template argument automatically:
```cpp
gpds::container c;
c.add_value("foo", 1337);   // integer
c.add_value("bar", 0.24);    // double
c.add_value("zbar", "Hello World");    // std::string
...
```

Earlier you stated that you also can't compile when explicitly stating the template type parameter so this can't really be the core issue anyway?

**Comment by Tectu** [comment]
This has been stale for a while.
In the meantime there are people successfully using this library with MSVC.
